name: flavorsync
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  appwrouter: ^0.2.7
  carousel_slider: ^5.0.0
  country_picker: ^2.0.27
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^4.2.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  multi_select_flutter: ^4.1.3
  permission_handler: ^11.3.1

dev_dependencies: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/kitchenAm.jpg" # Ruta de tu icono

flutter:
  uses-material-design: true
  assets:
    - assets/images/kitchenAm.jpg
    - assets/images/placeholder.png
